import { test, expect } from "@playwright/test";

test("board placement, connection editing and v1 migration persist", async ({ page }) => {
  const ids = ["E-case-001-hotel-room_notes-N-882", "E-case-001-access-access_logs-A-002"];
  const key = "null-case:case-001:investigation";
  await page.goto("/");
  await page.evaluate(({ ids, key }) => localStorage.setItem(key, JSON.stringify({ schemaVersion: 1, caseId: "case-001", caseSchemaVersion: 1, discoveredIds: ids, evidenceIds: ids, history: [] })), { ids, key });
  await page.reload();
  await page.getByRole("button", { name: "捜査を開始する" }).click();
  const board = page.getByRole("region", { name: "ケースボード", exact: true });
  await board.getByRole("button", { name: "404号室の運用メモ を配置", exact: true }).click();
  await board.getByRole("button", { name: "404号室の入室拒否ログ を配置", exact: true }).click();
  const node = board.getByRole("article", { name: "404号室の運用メモ", exact: true });
  await node.getByRole("button", { name: "下へ", exact: true }).focus();
  await page.keyboard.press("Enter");
  await expect(node).toContainText("列 1 / 行 2");
  await board.getByLabel("証拠A", { exact: true }).selectOption(ids[0]);
  await board.getByLabel("証拠B", { exact: true }).selectOption(ids[1]);
  await board.getByLabel("接続の種類", { exact: true }).selectOption("contradiction");
  await board.getByLabel("接続メモ", { exact: true }).fill("停止区画と入室記録を照合");
  await board.getByRole("button", { name: "接続を保存", exact: true }).click();
  await expect(board.locator(".boardLinks li")).toHaveCount(1);
  await expect(board.locator(".boardLinks")).toContainText("矛盾");
  await expect.poll(async () => page.evaluate((key) => JSON.parse(localStorage.getItem(key)!).board.links.length, key)).toBe(1);
  await page.reload();
  await page.getByRole("button", { name: "捜査を開始する" }).click();
  await expect(node).toContainText("列 1 / 行 2");
  await expect(board.locator(".boardLinks")).toContainText("停止区画と入室記録を照合");
  await board.getByRole("button", { name: "接続を編集", exact: true }).click();
  await board.getByLabel("接続の種類", { exact: true }).selectOption("relation");
  await board.getByLabel("接続メモ", { exact: true }).fill("<script>仮説</script>");
  await board.getByRole("button", { name: "接続を保存", exact: true }).click();
  await expect(board.locator(".boardLinks li")).toHaveCount(1);
  await expect(board.locator(".boardLinks")).toContainText("関係");
  await expect(board.locator(".boardLinks")).toContainText("<script>仮説</script>");
  await board.getByLabel("証拠B", { exact: true }).selectOption(ids[0]);
  await board.getByRole("button", { name: "接続を保存", exact: true }).click();
  await expect(board.locator(".error")).toBeVisible();
  await node.getByRole("button", { name: "ボードから外す", exact: true }).click();
  await expect(board.locator(".boardLinks li")).toHaveCount(0);
  await expect(board.locator(".boardNode")).toHaveCount(1);
  await expect(page.locator(".evidenceCard")).toHaveCount(2);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.reload();
  await page.getByRole("button", { name: "捜査を開始する" }).click();
  await expect(board.locator(".boardNode")).toHaveCount(1);
  await expect(board.locator(".boardLinks li")).toHaveCount(0);
});
